services:
  # postgres:
  #   container_name: postgres
  #   image: postgres:latest
  #   restart: always
  #   ports:
  #     - '5433:5432'
  #   environment:
  #     POSTGRES_USER: root
  #     POSTGRES_PASSWORD: root
  #     POSTGRES_DB: reg-sys
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  chroma:
    container_name: chromadb
    image: chromadb/chroma
    restart: always
    ports:
      - '8000:8000'
    volumes:
      - chroma_data:/data

  redis:
    container_name: redis
    image: redis:latest
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
      - redis_logs:/var/log/redis
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: ['redis-server', '/usr/local/etc/redis/redis.conf']
volumes:
  postgres_data:
  chroma_data:
  redis_data:
  redis_logs:
